dist: trusty
language: node_js
node_js:
  - 6
  - 8
  - 10
cache:
  yarn: true
  directories:
  - node_modules
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn global add greenkeeper-lockfile
install: yarn
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
script:
  - "./tests/e2e.sh"
