dist: trusty
language: node_js
node_js:
- 8
- 10
- 11
addons:
  sonarcloud:
    organization: "liangchunn-github"
    token:
      secure: "ZxBCm6+3YkoTujGPJjY9Hy5xZa1IZqtm8e9gQfJjLIW265nXgFtnOQ7Qy7YU5gLEqeZTQdAiGWRu7jG4V5HSyqzh7K+pE9WBdb8y3GS8VtQq+dmtk23+gJwKgwYscbVPY1HFnQgxhsBqCmpDydtcMyOkqda5MrWFfFuRRnv97Ft3ZWaBHCmmvQPrJYLb1ATnFmoZxXtYm6JosVXGHUmQ8IgbX2oes8Z1Gas7PqSd/1nQWN8nXPOdNl7Zt7oi9UkpdLOIrOnx+kTrxgwpqI8BObBedjOF34oOvKBC1rV9TWrUXNMlr6B0ekYbUHj3PtZDw19UA0jEMIIvSbrAPtOxaPuRV3x37cuQBoD57rCrz+MYIpIdLrjP8Seo0aBrvWI5QQzmtrucdHhokW9GLLPa/hY9lFvehEjX9xYsyWQxLgAjMC2xazRIJFG1SnXHVC23nbVp2LnnYzbWdG41u8PYKqgykzrxa58HGLcMnTEnQvp+AUHFnnp29Y530UBUm3ylWTfHmN5N2+TapnAzVpM2xBRto/iCBG2KP3pRJh2EH9wGlOQNEAAZKHOFx9h5Lv0DAii5J7T8wgjl4UfFx1KKDxDwkzwsLb2du9ZrQZ3cxznEFUKFwkTSb5/J/6M4etKuWZkcU7zuUWgSiVHc/u1yRfEx+yBx2/YSTpigA6eOnBk="
cache:
  yarn: true
  directories:
  - node_modules
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH="$HOME/.yarn/bin:$PATH"
- yarn global add greenkeeper-lockfile
install: yarn
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
script:
- yarn lint
- sonar-scanner
- "./tests/e2e.sh"
